name: Deply UAT Agent

on:
  push:
    branches:
      - "agent/uat/*"

jobs:
  build and deploy:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read agent_name from .agent_name
        run: echo "AGENT_NAME=$(grep AGENT_NAME .agent_name | cut -d '=' -f2 | xargs)" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get Access Token
        id: get_token
        run: echo "ACCESS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV

      - name: Call Google Cloud API
        run: |
          curl -f ${{ env.API_HOST }}/checkers \
            --header "Authorization: Bearer $ACCESS_TOKEN" \
            --header "Content-Type: application/json" \
            -d '{"name": "'"$AGENT_NAME"'", "type": "ai", "telegramId": null}'

      - name: Deploy cloud function with pubsub trigger
        run: |
          gcloud functions deploy agent_$AGENT_NAME \
            --gen2 \
            --runtime=python311 \
            --region=asia-southeast1 \
            --source=. \
            --entry-point=subscribe \
            --trigger-topic=${{ vars.TOPIC_NAME }} \
            --set-env-vars AGENT_NAME=$AGENT_NAME,API_HOST=${{ env.API_HOST }},WEBDRIVER_HOST=${{ env.WEBDRIVER_HOST}}
            --retry \
